# Site settings
title: "Sushant's Portfolio"
description: 'My portfolio of projects and experiences.'
baseurl: '' # the subpath of your site, e.g. /portfolio
url: 'https://sushantkadam15.github.io' # the base hostname & protocol for your site
lang: en

# Author settings
author:
    name: 'Sushant Kadam'
    email: 'your-email@example.com'
    url: 'https://sushantkadam15.github.io'

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-sitemap

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Navigation
nav:
    - home:
          url: /
          title: Home
    - projects:
          url: /projects
          title: Projects
    - about:
          url: /about
          title: About
    - contact:
          url: /contact
          title: Contact

# Social media
twitter_username: 'your_twitter_username'
github_username: 'sushantkadam15'
linkedin_username: 'your_linkedin_username'

# Excludes
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - node_modules
    - vendor

# Defaults
defaults:
    - scope:
          path: ''
          type: posts
      values:
          layout: post
          author: 'Sushant Kadam'
    - scope:
          path: ''
          type: pages
      values:
          layout: page
          author: 'Sushant Kadam'
    - scope:
          path: ''
          type: projects
      values:
          layout: project
          author: 'Sushant Kadam'

# Markdown settings
kramdown:
    input: GFM
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    syntax_highlighter_opts:
        default_lang: ruby
        line_numbers: true
        line_number_start: 1
        wrap: div
        bold_every: 10
        css: class
